# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='beer',
        ),
        migrations.AddField(
            model_name='menu',
            name='beer',
            field=models.ManyToManyField(to='app.Beer'),
        ),
    ]
