# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160826_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='beer',
            field=models.ManyToManyField(to='app.Beer'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
