# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160826_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='beer',
        ),
        migrations.AddField(
            model_name='beer',
            name='restaurant',
            field=models.ManyToManyField(to='app.Restaurant'),
        ),
    ]
